version: '3'

services:
  nginx:
    image: nginx
    environment:
      - VIRTUAL_HOST=gg.com
      - LETSENCRYPT_HOST=gg.com
      - LETSENCRYPT_EMAIL=my@main.com

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./current/public:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - ./current/public:/usr/share/nginx/html
    depends_on:
      - nginx-proxy

volumes:
  vhost:
networks:
  default:
    external:
      name: nginx-proxy-example